# Generated by Django 2.1.7 on 2019-03-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid1', models.IntegerField()),
                ('userid2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donut_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('csv_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='connectedpair',
            name='connected_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donut.Donut_Group'),
        ),
    ]
