# Generated by Django 2.1.7 on 2019-03-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut_group',
            name='frequency_in_days',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
